
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMA LPAREN LSB NAME RPAREN RSB STRexpr : STRexpr : LPAREN exprs RPARENexpr : LSB exprs RSBexprs : expr COMMA exprs\n             | expr COMMA\n             | expr\n    expr : NAME'
    
_lr_action_items = {'STR':([0,3,4,10,],[2,2,2,2,]),'LPAREN':([0,3,4,10,],[3,3,3,3,]),'LSB':([0,3,4,10,],[4,4,4,4,]),'NAME':([0,3,4,10,],[5,5,5,5,]),'$end':([1,2,5,9,11,],[0,-1,-7,-2,-3,]),'COMMA':([2,5,7,9,11,],[-1,-7,10,-2,-3,]),'RPAREN':([2,5,6,7,9,10,11,12,],[-1,-7,9,-6,-2,-5,-3,-4,]),'RSB':([2,5,7,8,9,10,11,12,],[-1,-7,-6,11,-2,-5,-3,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,3,4,10,],[1,7,7,7,]),'exprs':([3,4,10,],[6,8,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> STR','expr',1,'p_str','calc.py',850),
  ('expr -> LPAREN exprs RPAREN','expr',3,'p_tuple','calc.py',853),
  ('expr -> LSB exprs RSB','expr',3,'p_list','calc.py',857),
  ('exprs -> expr COMMA exprs','exprs',3,'p_exprs','calc.py',862),
  ('exprs -> expr COMMA','exprs',2,'p_exprs','calc.py',863),
  ('exprs -> expr','exprs',1,'p_exprs','calc.py',864),
  ('expr -> NAME','expr',1,'p_name','calc.py',874),
]
